%module "libring"
%{
#include "./contrib/ring-daemon/src/*.h"
%}
%include "./contrib/ring-daemon/src/logger.h"
%include "contrib/ring-daemon/src/account_factory.h"
%include "contrib/ring-daemon/src/map_utils.h"
%include "contrib/ring-daemon/src/account.h"      
%include "contrib/ring-daemon/src/noncopyable.h"
%include "contrib/ring-daemon/src/account_schema.h"
%include "contrib/ring-daemon/src/plugin_loader.h"
%include "contrib/ring-daemon/src/archiver.h"
%include "contrib/ring-daemon/src/plugin_manager.h"
%include "contrib/ring-daemon/src/array_size.h"
%include "contrib/ring-daemon/src/preferences.h"
%include "contrib/ring-daemon/src/base64.h"         
%include "contrib/ring-daemon/src/rational.h"
%include "contrib/ring-daemon/src/call_factory.h"        
%include "contrib/ring-daemon/src/registration_states.h"
%include "contrib/ring-daemon/src/call.h"                 
%include "contrib/ring-daemon/src/ring_plugin.h"
%include "contrib/ring-daemon/src/compiler_intrinsics.h"  
%include "contrib/ring-daemon/src/ring_types.h"
%include "contrib/ring-daemon/src/conference.h"           
%include "contrib/ring-daemon/src/rw_mutex.h"
%include "contrib/ring-daemon/src/dlfcn.h"                
%include "contrib/ring-daemon/src/smartools.h"
%include "contrib/ring-daemon/src/enumclass_utils.h"      
%include "contrib/ring-daemon/src/string_utils.h"
%include "contrib/ring-daemon/src/fileutils.h"            
%include "contrib/ring-daemon/src/threadloop.h"
%include "contrib/ring-daemon/src/ice_socket.h"           
%include "contrib/ring-daemon/src/thread_pool.h"
%include "contrib/ring-daemon/src/ice_transport.h"        
%include "contrib/ring-daemon/src/utf8_utils.h"
%include "contrib/ring-daemon/src/ip_utils.h"             
%include "contrib/ring-daemon/src/windirent.h"
%include "contrib/ring-daemon/src/logger.h"              
%include "contrib/ring-daemon/src/winsyslog.h"
%include "contrib/ring-daemon/src/manager.h"

%include "contrib/ring-daemon/src/client/ring_signal.h"
%include "contrib/ring-daemon/src/client/videomanager.h"

%include "contrib/ring-daemon/src/config/serializable.h"
%include "contrib/ring-daemon/src/config/yamlparser.h"

%include "contrib/ring-daemon/src/dring/account_const.h"
%include "contrib/ring-daemon/src/dring/call_const.h"
%include "contrib/ring-daemon/src/dring/callmanager_interface.h"
%include "contrib/ring-daemon/src/dring/configurationmanager_interface.h"
%include "contrib/ring-daemon/src/dring/dring.h"
%include "contrib/ring-daemon/src/dring/media_const.h"
%include "contrib/ring-daemon/src/dring/presencemanager_interface.h"
%include "contrib/ring-daemon/src/dring/security_const.h"
%include "contrib/ring-daemon/src/dring/videomanager_interface.h"

%include "contrib/ring-daemon/src/hooks/urlhook.h"

%include "contrib/ring-daemon/src/im/instant_messaging.h"
%include "contrib/ring-daemon/src/im/message_engine.h"

%include "contrib/ring-daemon/src/media/libav_deps.h"
%include "contrib/ring-daemon/src/media/libav_utils.h"
%include "contrib/ring-daemon/src/media/media_buffer.h"
%include "contrib/ring-daemon/src/media/media_codec.h"
%include "contrib/ring-daemon/src/media/media_decoder.h"
%include "contrib/ring-daemon/src/media/media_device.h"
%include "contrib/ring-daemon/src/media/media_encoder.h"
%include "contrib/ring-daemon/src/media/media_io_handle.h"
%include "contrib/ring-daemon/src/media/recordable.h"
%include "contrib/ring-daemon/src/media/rtp_session.h"
%include "contrib/ring-daemon/src/media/socket_pair.h"
%include "contrib/ring-daemon/src/media/srtp.h"
%include "contrib/ring-daemon/src/media/system_codec_container.h"

%include "contrib/ring-daemon/src/ringdht/namedirectory.h"
%include "contrib/ring-daemon/src/ringdht/ringaccount.h"
%include "contrib/ring-daemon/src/ringdht/sips_transport_ice.h"
%include "contrib/ring-daemon/src/ringdht/sip_transport_ice.h"


%include "contrib/ring-daemon/src/security/certstore.h"
%include "contrib/ring-daemon/src/security/tls_session.h"
%include "contrib/ring-daemon/src/security/tlsvalidator.h"

%include "contrib/ring-daemon/src/sip/pattern.h"
%include "contrib/ring-daemon/src/sip/pres_sub_client.h"
%include "contrib/ring-daemon/src/sip/pres_sub_server.h"
%include "contrib/ring-daemon/src/sip/sdes_negotiator.h"
%include "contrib/ring-daemon/src/sip/sdp.h"
%include "contrib/ring-daemon/src/sip/sipaccountbase.h"
%include "contrib/ring-daemon/src/sip/sipaccount.h"
%include "contrib/ring-daemon/src/sip/sipcall.h"
%include "contrib/ring-daemon/src/sip/sippresence.h"
%include "contrib/ring-daemon/src/sip/siptransport.h"
%include "contrib/ring-daemon/src/sip/sip_utils.h"
%include "contrib/ring-daemon/src/sip/sipvoiplink.h"

%include "contrib/ring-daemon/src/upnp/upnp_context.h"
%include "contrib/ring-daemon/src/upnp/upnp_control.h"
%include "contrib/ring-daemon/src/upnp/upnp_igd.h"